# .github/workflows/example-2.yml

name: Manual Inputs
on:
  workflow_dispatch:
    inputs:
      brand:
        description: Bump brand
        default: MyPhone
        required: true
      version:
        description: Bump Version
        default: v1.0.0
        required: true
      env:
        description: Bump Version
        default: stage
        required: true
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Example variable usage
        run: git tag ${{ github.event.inputs.version }}
