# .github/workflows/example-2.yml

name: Manual Inputs
on:
  workflow_dispatch:
    inputs:
      brand:
        description: Bump brand
        default: MyPhone
        required: true
      version:
        description: Bump Version
        required: false
      env:
        description: Bump Version
        default: stage
        required: true
      password:
        description: Password
        required: true
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:

      - name: Check Passowrd
        run: echo ${{ secrets.PASSWORD }}

      - name: Check out Git repository
        uses: actions/checkout@v2
      # Optionally: unshallow as a separate operation
      # - name: Unshallow
      #   run: git fetch --prune --unshallow
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
      - name: Set Brand from inputs
        run: |
          node config/brands/index.js --brand=${{ github.event.inputs.brand }} --env=${{github.event.inputs.env}}
