# .github/workflows/example-2.yml

name: Manual Inputs
on:
  workflow_dispatch:
    inputs:
      brand:
        description: Bump brand
        default: MyPhone
        required: true
      version:
        description: Bump Version
        default: v1.0.0
        required: true
      env:
        description: Bump Version
        default: stage
        required: true
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      # Optionally: unshallow as a separate operation
      # - name: Unshallow
      #   run: git fetch --prune --unshallow
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
          # if you unshallow in a separate step, use the following option:
          # skip-unshallow: 'true'
      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
